baseurl: /create-story-template

# Site
name: "Sddtc"
title: "Sddtc's web"
description: "子标题"
logo: 'Logo'

# Pagination
paginate: 9
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate

# Other
markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
